### ISSUE TITLE
TLCL的下载链接已坏 望修正

### ISSUE THREAD

**Issue by h4n0** [billie66/billie66.github.com#2]
http://billie66.github.io/TLCL/index.html 下的下载中英文和中文pdf的链接已经失效 希望更新到新链接

**Comment by billie66** [comment]
本书的 PDF 将会移到百度网盘

**Comment by billie66** [comment]
中英文地址： http://pan.baidu.com/s/1pJ4zcVL

中文地址： http://pan.baidu.com/s/1i3rKcEL

**Comment by h4n0** [comment]
多谢!

**Comment by lsh2333** [comment]
你好，中文版链接被百度云和谐了
